### ISSUE TITLE
No way to reset values selected in component.

### ISSUE THREAD

**Issue by Devoamos1** [TatuLund/TwinColSelect#1]
There is no way at the moment to reset the values selected via current methods, only by using built-in buttons on the component. The requirement is to clear all selected items via a button click. 

Methods attempted are 

.clear();
.deselectAll();

**Comment by TatuLund** [comment]
This is fixed by https://github.com/TatuLund/TwinColSelect/commit/b634e53b49ddaafe638f12bd8fa861a10f80e69c in version 1.2.3, which is now also in Directory
