### ISSUE TITLE
Typo in twincolselect.css prevents use in vaadin 14.6 / vaadin-plugin 0.14.6.0

### ISSUE THREAD

**Issue by mthome** [TatuLund/TwinColSelect#10]
The following line:
https://github.com/TatuLund/TwinColSelect/blob/b50bbb7151ed68f2e67a1c9ceca8a4c446489fff/src/main/resources/META-INF/resources/frontend/twincolselect.css#L8

Results in a compiletime (really frontend) build:
`  ERROR in ../node_modules/@vaadin/flow-frontend/twincolselect.css
  Module build failed (from ../node_modules/.pnpm/css-loader@4.2.1_webpack@4.42.0/node_modules/css-loader/dist/cjs.js):
  CssSyntaxError
  
  (8:40) Unclosed string
  
     6 | .twincolselect-errorlabel {
     7 |        color: var(--lumo-error-text-color);
  >  8 |     font-size: var(--lumo-font-size-xs)");
       |                                        ^
     9 |     line-height: var(--lumo-line-height-xs);
    10 |     will-change: max-height;
  
   @ ../target/frontend/generated-flow-imports.js?babel-target=es6 35:0-62 36:36-43`

**Comment by TatuLund** [comment]
Good catch and luckily easy to fix ... I am just impressed why this did not fail with earlier versions.
