### ISSUE TITLE
Add/Remove Buttons Refresh broken

### ISSUE THREAD

**Issue by ssi-ips** [TatuLund/TwinColSelect#16]
I needed to update the addon to 2.2.0 because we updated Vaadin to 23.1. It looks like refresh of the Buttons is broken. 

- Initially all Buttons are disabled. The "Add All" Buttons should be enabled, because adding all Items should be possible as long that still one is left.
- When one item is selected, no buttons become active. "Add" should be active
- When Items are added (double click works), the "Remove" Button is active, even if no item is selected. Nothing happens when clicked.
- The "Add" Button is active even when no item is selected (after it became active after the first refresh after the items were added)

I think the safest way is to refresh the buttons on every (de-)select and item list modificaion. The "Add" and "Remove buttons should only be active when a item is selected on the respective side.

**Comment by TatuLund** [comment]
I released version 2.2.1, check if it works properly.
