### ISSUE TITLE
Styling is pretty hard

### ISSUE THREAD

**Issue by ssi-ips** [TatuLund/TwinColSelect#17]
Changing the default style of the component is pretty hard (or even impossible) for some properties because they a directly added to the style-attribute of the component, e.g. background of the vertical layout. It would be better to move the styles to css and handle the changes through different css-classes.

**Comment by TatuLund** [comment]
I added some css samples. The latest version has class names for value and options layouts as well.

https://github.com/TatuLund/TwinColSelect/blob/nextlts/frontend/themes/mytheme/styles.css

Outcome:

![image](https://user-images.githubusercontent.com/14309836/205884840-ef435db7-5346-4c04-923b-62455293d0c8.png)
