### ISSUE TITLE
TwinColSelect and binder in readonly mode does not make the TwinColSelect readonly

### ISSUE THREAD

**Issue by thomasdewaelheyns** [TatuLund/TwinColSelect#3]
I have strange behaviour with this component and a binder that is set as binder.readOnly(true).
The expected behaviour is that the twinColSelect component would act the same as the vaadin field ones and not allow the user to change selections. Some of the behaviour is there but there seems to be some strange workarounds. Please see the attached gif with an illustration.
![K8wtrJS47m](https://user-images.githubusercontent.com/1107343/84908748-25ebc900-b0b5-11ea-8df0-31e4153377f1.gif)

**Comment by TatuLund** [comment]
Thanks for reporting this. I need to take a closer look.

**Comment by TatuLund** [comment]
Yes, readOnly handling was completely missing.

**Comment by TatuLund** [comment]
Fixed in version 1.3.1
