### ISSUE TITLE
DataProvider filtering incorrectly clears previously selected choices

### ISSUE THREAD

**Issue by mthome** [TatuLund/TwinColSelect#5]
We use TwinColSelect to allow a multi select a small number of values from sometimes several hundred options.  In order t help the user manage large numbers of options, we use a DataProvider with a dynamic filter, but the current definitions of setDataProvider (the dataproviderlistener) and sortDestinationList discard from the selected  items list any previously selected values that are not in the currently filtered dataprovider.

Example:

- unfiltered dataprovider contains: AA, AB, AC, XX, XY, XZ.
- I select XX (moving it to the right hand side)
- I apply a filter to my data provider limiting to items starting with A -> the right hand side is **cleared**, the left has AA,AB,AC
- I select AA and move to the right 
- exit the dialog -> the value is [AA] - my **explicit** selection of XX was discarded.

Expectation:
1. filtering the dataprovider should never clear previously selected items.
2. sorting the target list should not clear previously selected items.
3. it is okay to hide selected items.

**Comment by TatuLund** [comment]
Fixed in 1.6.0
