### ISSUE TITLE
Convenience workflow accelerators

### ISSUE THREAD

**Issue by mthome** [TatuLund/TwinColSelect#7]
User requested features, mostly to match the older Vaadin Framework behavior:

- double click on an item moves it to the other list.
- click on item a, shift click on item b will select all items visible from a to b (inclusive) if a and b are in the same list.
- make the "trash" button more useful by making it clear all in a list if there are any selected, but if none are selected it selects all, making it into a bulk select/deselect.  I did not change the trash icon, though there is probably a better choice now - perhaps recycle?

I've forked and committed the above changes in separate commits at:  https://github.com/mthome/TwinColSelect

I think the checkbox at the of the middle panel no longer has any use with functional range select.

**Comment by TatuLund** [comment]
Hi, Thanks for you contributions. I will look thru them and include to Directory version.

> I think the checkbox at the of the middle panel no longer has any use with functional range select.

Yes, probably not.

**Comment by TatuLund** [comment]
> click on item a, shift click on item b will select all items visible from a to b (inclusive) if a and b are in the same list.

This solution looks neat. I need to test it in action.

**Comment by mthome** [comment]
Thanks, Tatu - note my inline comments.  In particular:

- I strongly dislike the casting required when the checkboxes need to call out to the enclosing class.  It is safe given the context, but it would be better to retain full type safety.
- the range select feature might benefit from UX eyes - I'm went back and forth exactly what the behavior should be - in particular, what if anything should happen to items outside the selection range.  I'm also not entirely happy with the implementation but I couldn't figure out a nicer one - perhaps you can.
